title: QuestPDF Companion
code-sign:
  signing-identity: "Apple Distribution: Marcin Ziabek (L57GK9Y59F)"
  identifier: "com.questpdf.companion"
contents:
  - x: 448
    y: 192
    type: link
    path: "/Applications"
  - x: 192
    y: 192
    type: file
    path: QuestPDF Companion.app